//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RimWorldSaveManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RimWorldSaveManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Backstories&gt;
        ///
        ///	&lt;Backstory&gt;
        ///		&lt;Title&gt;Colony settler&lt;/Title&gt;
        ///		&lt;TitleShort&gt;Settler&lt;/TitleShort&gt;
        ///		&lt;BaseDesc&gt;NAME was a settler on a new colony world.\n\nSuch a life requires a jack-of-all trades at basic hands-on tasks.&lt;/BaseDesc&gt;
        ///		&lt;Slot&gt;Adulthood&lt;/Slot&gt;
        ///		&lt;SkillGains&gt;
        ///			&lt;li&gt;&lt;key&gt;Construction&lt;/key&gt;&lt;value&gt;4&lt;/value&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;key&gt;Growing&lt;/key&gt;&lt;value&gt;4&lt;/value&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;key&gt;Mining&lt;/key&gt;&lt;value&gt;4&lt;/value&gt;&lt;/li&gt;
        ///		&lt;/SkillGains&gt;
        ///		&lt;SpawnCategories&gt;
        ///			&lt;li&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdulthoodsCivil {
            get {
                return ResourceManager.GetString("AdulthoodsCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///
        ///&lt;Backstories&gt;
        ///
        ///	&lt;Backstory&gt;
        ///		&lt;Title&gt;Space pirate&lt;/Title&gt;
        ///		&lt;TitleShort&gt;Pirate&lt;/TitleShort&gt;
        ///		&lt;BaseDesc&gt;Piracy appears everywhere that governments are weak and society spread thin. NAME was part of this age-old part of human existence, extorting and smashing peaceful trade ships for profit.&lt;/BaseDesc&gt;
        ///		&lt;Slot&gt;Adulthood&lt;/Slot&gt;
        ///		&lt;SkillGains&gt;
        ///			&lt;li&gt;&lt;key&gt;Melee&lt;/key&gt;&lt;value&gt;4&lt;/value&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;key&gt;Shooting&lt;/key&gt;&lt;value&gt;4&lt;/value&gt;&lt;/li&gt;
        ///		&lt;/SkillGains&gt;
        ///		&lt;Sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdulthoodsRaider {
            get {
                return ResourceManager.GetString("AdulthoodsRaider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;BackstoryTranslations&gt;
        ///	&lt;ColonySettler43&gt;
        ///		&lt;Title&gt;Colony settler&lt;/Title&gt;
        ///		&lt;TitleShort&gt;Settler&lt;/TitleShort&gt;
        ///		&lt;BaseDesc&gt;NAME was a settler on a new colony world.
        ///
        ///Such a life requires a jack-of-all trades at basic hands-on tasks.&lt;/BaseDesc&gt;
        ///	&lt;/ColonySettler43&gt;
        ///	&lt;MedievalFarmOaf58&gt;
        ///		&lt;Title&gt;Medieval farm oaf&lt;/Title&gt;
        ///		&lt;TitleShort&gt;Oaf&lt;/TitleShort&gt;
        ///		&lt;BaseDesc&gt;Tilling, hoeing, guiding ox carts, pushing wheelbarrows. Digging ditches, planting seeds, predictin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Backstories {
            get {
                return ResourceManager.GetString("Backstories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Backstories&gt;
        ///
        ///  &lt;Backstory&gt;
        ///    &lt;Title&gt;Medieval slave&lt;/Title&gt;
        ///		&lt;titleShort&gt;Slave&lt;/titleShort&gt;
        ///		&lt;BaseDesc&gt;NAME grew up pulling carts and digging holes on a medieval world. Simple manual labor is HIS oldest companion - along with the master&apos;s lash.\n\nHECAP didn&apos;t learn to read until age nine.&lt;/BaseDesc&gt;
        ///    &lt;Slot&gt;Childhood&lt;/Slot&gt;
        ///    &lt;SkillGains&gt;
        ///      &lt;li&gt;
        ///        &lt;key&gt;Growing&lt;/key&gt;
        ///        &lt;value&gt;2&lt;/value&gt;
        ///      &lt;/li&gt;
        ///      &lt;li&gt;
        ///        &lt;key&gt;Construc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Childhoods {
            get {
                return ResourceManager.GetString("Childhoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Backstories&gt;
        ///
        ///	&lt;Backstory&gt;
        ///		&lt;Title&gt;Hermit&lt;/Title&gt;
        ///		&lt;TitleShort&gt;Hermit&lt;/TitleShort&gt;
        ///		&lt;BaseDesc&gt;Worn out by the pressures of social interaction, NAME left HIS crowded midworld city to live a simple life in the wilderness. There, HE spent HIS days alone, tending HIS garden and crafting the simple tools HE needed to survive.&lt;/BaseDesc&gt;
        ///		&lt;Slot&gt;Adulthood&lt;/Slot&gt;
        ///		&lt;WorkDisables&gt;
        ///			&lt;li&gt;Social&lt;/li&gt;
        ///		&lt;/WorkDisables&gt;
        ///		&lt;SkillGains&gt;
        ///			&lt;li&gt;
        ///				&lt;key&gt;Growing&lt;/k [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtraA {
            get {
                return ResourceManager.GetString("ExtraA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Backstories&gt;
        ///
        ///	&lt;Backstory&gt;
        ///		&lt;Title&gt;Hiveworld drone&lt;/Title&gt;
        ///		&lt;TitleShort&gt;Drone&lt;/TitleShort&gt;
        ///		&lt;BaseDesc&gt;NAME worked as a mindless construction drone in a massive hiveworld civilization. Though HE is now freed from the brutal social experiments to which HE was subjected, HE remains incapable of creative thought and leadership.&lt;/BaseDesc&gt;
        ///		&lt;Slot&gt;Adulthood&lt;/Slot&gt;
        ///		&lt;WorkDisables&gt;
        ///			&lt;li&gt;Artistic&lt;/li&gt;
        ///			&lt;li&gt;Intellectual&lt;/li&gt;
        ///		&lt;/WorkDisables&gt;
        ///		&lt;requiredWo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtraB {
            get {
                return ResourceManager.GetString("ExtraB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Backstories&gt;
        ///
        ///  &lt;Backstory&gt;
        ///    &lt;Title&gt;Pyromaniac&lt;/Title&gt;
        ///    &lt;TitleShort&gt;Pyro&lt;/TitleShort&gt;
        ///    &lt;BaseDesc&gt;From an early age, NAME had an unhealthy fascination with fire. HECAP would set refuse heaps ablaze and become so entranced by the flames HE would absent-mindedly burn HIMself.\n\nOne day while playing with matches, HE carelessly burned down HIS home.&lt;/BaseDesc&gt;
        ///    &lt;Slot&gt;Childhood&lt;/Slot&gt;
        ///    &lt;WorkDisables&gt;
        ///      &lt;li&gt;Firefighting&lt;/li&gt;
        ///    &lt;/WorkDisables [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtraC {
            get {
                return ResourceManager.GetString("ExtraC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Backstories&gt;
        ///
        ///	&lt;Backstory&gt;
        ///		&lt;Title&gt;Convent child&lt;/Title&gt;
        ///		&lt;titleShort&gt;Illicit&lt;/titleShort&gt;
        ///		&lt;BaseDesc&gt;The child of an illicit affair, NAME was bought up by nuns in a medieval convent. HECAP learned the value of hard work and submission, but was taught that technology is heretical.&lt;/BaseDesc&gt;
        ///		&lt;Slot&gt;Childhood&lt;/Slot&gt;
        ///		&lt;WorkDisables&gt;
        ///			&lt;li&gt;Intellectual&lt;/li&gt;
        ///			&lt;li&gt;Violent&lt;/li&gt;
        ///		&lt;/WorkDisables&gt;
        ///		&lt;SkillGains&gt;
        ///			&lt;li&gt;&lt;key&gt;Construction&lt;/key&gt;&lt;value&gt;3&lt;/va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtraD {
            get {
                return ResourceManager.GetString("ExtraD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PlayerCreatedBios&gt;
        ///	&lt;PawnBio&gt;
        ///		&lt;Name&gt;
        ///			&lt;First&gt;James&lt;/First&gt;
        ///			&lt;Last&gt;Grey&lt;/Last&gt;
        ///			&lt;Nick&gt;Doc&lt;/Nick&gt;
        ///		&lt;/Name&gt;
        ///		&lt;Gender&gt;Male&lt;/Gender&gt;
        ///		&lt;PirateKing&gt;True&lt;/PirateKing&gt;
        ///		&lt;Childhood&gt;
        ///			&lt;Title&gt;Fallen prodigy&lt;/Title&gt;
        ///			&lt;TitleShort&gt;Prodigy&lt;/TitleShort&gt;
        ///			&lt;BaseDesc&gt;NAME was born on a glitterworld falling into chaos. HISCAP father was killed in action.
        ///
        ///HECAP struggled for a scholarship at Utmaior Academy and had to prove his right to be there. A child  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rimworld_creations {
            get {
                return ResourceManager.GetString("rimworld_creations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Backstories&gt;
        ///
        ///&lt;Backstory&gt;
        ///	&lt;Title&gt;Con artist&lt;/Title&gt;
        ///	&lt;TitleShort&gt;Con artist&lt;/TitleShort&gt;
        ///	&lt;BaseDesc&gt;NAME never created anything in HIS life. HECAP did, however, prove to be a natural at getting others to give HIM what they had created.&lt;/BaseDesc&gt;
        ///	&lt;Slot&gt;Adulthood&lt;/Slot&gt;
        ///	&lt;SkillGains&gt;
        ///		&lt;li&gt;
        ///			&lt;key&gt;Social&lt;/key&gt;
        ///			&lt;value&gt;10&lt;/value&gt;
        ///		&lt;/li&gt;
        ///	&lt;/SkillGains&gt;
        ///	&lt;SpawnCategories&gt;
        ///		&lt;li&gt;Trader&lt;/li&gt;
        ///		&lt;li&gt;Slave&lt;/li&gt;
        ///	&lt;/SpawnCategories&gt;
        ///	&lt;BodyTypeMale&gt;Male&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Travelers {
            get {
                return ResourceManager.GetString("Travelers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Backstories&gt;
        ///  
        ///	&lt;Backstory&gt;
        ///		&lt;Title&gt;Gatherer&lt;/Title&gt;
        ///		&lt;TitleShort&gt;Gatherer&lt;/TitleShort&gt;
        ///		&lt;BaseDesc&gt;NAME is a master gatherer. HECAP can find food in the most barren of places using HIS deep knowledge of plants, roots, and berries.&lt;/BaseDesc&gt;
        ///		&lt;Slot&gt;Adulthood&lt;/Slot&gt;
        ///		&lt;requiredWorkTags&gt;
        ///			&lt;li&gt;PlantWork&lt;/li&gt;
        ///		&lt;/requiredWorkTags&gt;
        ///		&lt;SkillGains&gt;
        ///			&lt;li&gt;
        ///				&lt;key&gt;Growing&lt;/key&gt;
        ///				&lt;value&gt;4&lt;/value&gt;
        ///			&lt;/li&gt;
        ///		&lt;/SkillGains&gt;
        ///		&lt;SpawnCategories&gt;
        ///			&lt;l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribalAdulthoodsA {
            get {
                return ResourceManager.GetString("TribalAdulthoodsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Backstories&gt;
        ///
        ///  &lt;Backstory&gt;
        ///    &lt;Title&gt;Abandoned child&lt;/Title&gt;
        ///    &lt;TitleShort&gt;Abandoned&lt;/TitleShort&gt;
        ///    &lt;BaseDesc&gt;NAME was born sickly. Thinking that HE would only burden the tribe, HIS parents left HIM out in the elements. Somehow, HE survived.&lt;/BaseDesc&gt;
        ///    &lt;Slot&gt;Childhood&lt;/Slot&gt;
        ///    &lt;WorkDisables&gt;
        ///    &lt;/WorkDisables&gt;
        ///    &lt;SkillGains&gt;
        ///      &lt;li&gt;
        ///        &lt;key&gt;Melee&lt;/key&gt;
        ///        &lt;value&gt;3&lt;/value&gt;
        ///      &lt;/li&gt;
        ///      &lt;li&gt;
        ///        &lt;key&gt;Crafting&lt;/key&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribalB {
            get {
                return ResourceManager.GetString("TribalB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Backstories&gt;
        ///
        ///	&lt;Backstory&gt;
        ///		&lt;Title&gt;Tribe child&lt;/Title&gt;
        ///		&lt;titleShort&gt;Tribal&lt;/titleShort&gt;
        ///		&lt;BaseDesc&gt;NAME grew up in the tribe, running around the village, moving with the muffalo herds, learning essential skills from HIS parents.\n\nHECAP never learned to read and never saw a machine that wasn&apos;t an ancient ruin.&lt;/BaseDesc&gt;
        ///		&lt;Slot&gt;Childhood&lt;/Slot&gt;
        ///		&lt;SkillGains&gt;
        ///			&lt;li&gt;
        ///				&lt;key&gt;Growing&lt;/key&gt;
        ///				&lt;value&gt;2&lt;/value&gt;
        ///			&lt;/li&gt;
        ///			&lt;li&gt;
        ///				&lt;key&gt;Melee&lt;/key&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TribalChildhoodsA {
            get {
                return ResourceManager.GetString("TribalChildhoodsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PlayerCreatedBios&gt;
        ///
        ///	&lt;PawnBio&gt;
        ///		&lt;Name&gt;
        ///			&lt;First&gt;Tynan&lt;/First&gt;
        ///			&lt;Last&gt;Sylvester&lt;/Last&gt;
        ///			&lt;Nick&gt;Tynan&lt;/Nick&gt;
        ///		&lt;/Name&gt;
        ///		&lt;Gender&gt;Male&lt;/Gender&gt;
        ///		&lt;Childhood&gt;
        ///			&lt;Title&gt;Punk&lt;/Title&gt;
        ///			&lt;titleShort&gt;Punk&lt;/titleShort&gt;
        ///			&lt;BaseDesc&gt;NAME spent his childhood selling knockoff cigarettes to 15-year-olds. The cigarettes were often full of grass clippings.&lt;/BaseDesc&gt;
        ///			&lt;SkillGains&gt;
        ///				&lt;li&gt;
        ///					&lt;key&gt;Research&lt;/key&gt;
        ///					&lt;value&gt;-2&lt;/value&gt;
        ///				&lt;/li&gt;
        ///				&lt;li&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TynanCustom {
            get {
                return ResourceManager.GetString("TynanCustom", resourceCulture);
            }
        }
    }
}
